####################
# CTscanner system #
####################
/gate/world/daughters/name CTscanner
/gate/world/daughters/insert box
/gate/CTscanner/placement/setTranslation 0. 0. -257. mm
#/gate/CTscanner/geometry/setXLength 195.072 mm
#/gate/CTscanner/geometry/setYLength 243.84 mm

#sample 
/gate/CTscanner/geometry/setXLength 300 mm
/gate/CTscanner/geometry/setYLength 300 mm


#/gate/CTscanner/geometry/setXLength 195. mm
#/gate/CTscanner/geometry/setYLength 243. mm


/gate/CTscanner/geometry/setZLength 1. mm
/gate/CTscanner/setMaterial Air
/gate/CTscanner/vis/forceWireframe
/gate/CTscanner/vis/setColor white

#############           ############
# CTSCANNER #   ---->   #  MODULE  #
#############           ############
/gate/CTscanner/daughters/name module
/gate/CTscanner/daughters/insert box
#/gate/module/geometry/setXLength 195.072 mm
#/gate/module/geometry/setYLength 243.84 mm

#sample
/gate/module/geometry/setXLength 300 mm
/gate/module/geometry/setYLength 300 mm

#/gate/module/geometry/setXLength 195. mm
#/gate/module/geometry/setYLength 243. mm

/gate/module/geometry/setZLength  1. mm
/gate/module/setMaterial Silicon
/gate/module/vis/forceWireframe
/gate/module/vis/setColor white

# ATTACH SYSTEM
/gate/systems/CTscanner/module/attach module

# ATTACH LAYER
/gate/module/attachCrystalSD
